# Generated by Django 5.2.8 on 2025-11-21 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=210)),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=210)),
            ],
        ),
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambiente', to='sensores.local')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensores.responsavel')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('idSensor', models.AutoField(primary_key=True, serialize=False)),
                ('tipoSensor', models.CharField(choices=[('temperatura', 'Temperatura'), ('luminosidade', 'Luminosidade'), ('umidade', 'Umidade'), ('contador', 'Contador')], max_length=25)),
                ('identifSensor', models.CharField(max_length=110, unique=True)),
                ('unidadeMedSensor', models.CharField(blank=True, max_length=25)),
                ('latitudeSensor', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitudeSensor', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('statusSensor', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=12)),
                ('timestampSensor', models.DateTimeField(auto_now_add=True)),
                ('ambienteSensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensores.ambiente')),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ambiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensores.ambiente')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='sensores.sensor')),
            ],
        ),
    ]
